<p style="margin-bottom: 11.25pt; text-align: center;"><span style="font-size: 31.5pt; font-family: 'proxima_nova_rgbold',serif;">Anti-Spam Policy</span></p>
<p style="margin-bottom: 15.0pt;"><span style="font-size: 13.5pt; font-family: 'Arial',sans-serif;">This policy is applicable to all IBuumerang (IBuumerang) services (&ldquo;Covered Services&rdquo;).</span></p>
<p style="margin-bottom: 15.0pt;"><span style="font-size: 13.5pt; font-family: 'Arial',sans-serif;">You agree to this Anti-Spam Policy as a precondition to use of Covered Services. We are very serious about our Anti-Spam Policy. If we discover that you are sending emails or messages to people without their permission, we reserve the right to terminate your user account.</span></p>
<p style="margin-bottom: 15.0pt;"><span style="font-size: 13.5pt; font-family: 'Arial',sans-serif;">By &ldquo;</span><span style="font-size: 13.5pt; font-family: 'Arial',sans-serif;">permission</span><span style="font-size: 13.5pt; font-family: 'Arial',sans-serif;">&rdquo; we mean express and provable permission granted to you. A permission to send commercial emails may be through:</span></p>
<ul>
    <li style="margin-left: .25in; text-indent: -.25in; tab-stops: .5in;"><span style="font-size: 13.5pt; font-family: 'Arial',sans-serif;">Submission of email address as part of downloading anything from your website or ordering a product or service from you.</span></li>
    <li style="margin-left: .25in; text-indent: -.25in; tab-stops: .5in;"><span style="font-size: 13.5pt; font-family: 'Arial',sans-serif;">Subscription to an email newsletter by filling a form on your website.</span></li>
    <li style="margin-left: .25in; text-indent: -.25in; tab-stops: .5in;"><span style="font-size: 13.5pt; font-family: 'Arial',sans-serif;">Someone has provided you with the email address as part of participation in any contest, event or survey conducted by you and you have informed him/her that you would be sending them marketing emails.</span></li>
    <li style="margin-left: .25in; text-indent: -.25in; tab-stops: .5in;"><span style="font-size: 13.5pt; font-family: 'Arial',sans-serif;">Any instance where a person completing a form has checked an opt-in checkbox indicating their willingness to be contacted by you through email, provided the checkbox is unchecked by default and you have informed such person that the nature of the emails will be commercial.</span></li>
    <li style="margin-left: .25in; text-indent: -.25in; tab-stops: .5in;"><span style="font-size: 13.5pt; font-family: 'Arial',sans-serif;">Any business card given by a person who has expressed his/her willingness to receive emails of a commercial nature. Willingness to receive emails of a commercial nature will be presumed where the business card was dropped in your booth at a tradeshow.</span></li>
</ul>
<p style="margin-bottom: 15.0pt;"><span style="font-size: 13.5pt; font-family: 'Arial',sans-serif;">The rule of thumb is &ldquo;Do not send emails or messages to email addresses to which you do not have express permission to send emails on the subject of the email.&rdquo; We insist on 100% compliance with the above rule.</span></p>
<p style="margin-bottom: 15.0pt;"><span style="font-size: 13.5pt; font-family: 'Arial',sans-serif;">When we say 100%, we do not include those instances where the recipient of an email has marked it as Spam although you have an express provable permission to send emails to that email address. It should be borne in mind that a permission once granted is deemed to have been revoked if the recipient of an email has opted out of receiving emails from you.</span></p>
<p style="margin-bottom: 15.0pt;"><span style="font-size: 13.5pt; font-family: 'Arial',sans-serif;">In particular, you shall strictly comply with the following rules, which clarify the Rule of Thumb mentioned above:</span></p>
<ul>
    <li style="margin-left: .25in; text-indent: -.25in; tab-stops: .5in;"><span style="font-size: 13.5pt; font-family: 'Arial',sans-serif;">You should have explicit permission to contact the recipient on the subject of your email. You shall maintain sufficient proof of the fact that you have received permission from all recipients of emails sent by you.</span></li>
    <li style="margin-left: .25in; text-indent: -.25in; tab-stops: .5in;"><span style="font-size: 13.5pt; font-family: 'Arial',sans-serif;">You shall not import or send emails to email addresses that you have bought, loaned, rented or in any way acquired from a third party, irrespective of any claim about quality or permission. You shall also refrain from importing or sending emails to email addresses you have collected from other websites.</span></li>
    <li style="margin-left: .25in; text-indent: -.25in; tab-stops: .5in;"><span style="font-size: 13.5pt; font-family: 'Arial',sans-serif;">You shall ensure that the routing and header information including your emails &ldquo;From&rdquo; and &ldquo;To,&rdquo; the originating domain name and email address are true and accurate.</span></li>
    <li style="margin-left: .25in; text-indent: -.25in; tab-stops: .5in;"><span style="font-size: 13.5pt; font-family: 'Arial',sans-serif;">You shall not use subject lines that mislead the recipient about the contents or subject matter of the message.</span></li>
    <li style="margin-left: .25in; text-indent: -.25in; tab-stops: .5in;"><span style="font-size: 13.5pt; font-family: 'Arial',sans-serif;">You shall provide a one-click unsubscribe option in all emails and refrain from sending emails to persons who have opted out or un-subscribed from your mailing list. The request to opt-out from the mailing list should be honored within 10 days from the date of request.</span></li>
    <li style="margin-left: .25in; text-indent: -.25in; tab-stops: .5in;"><span style="font-size: 13.5pt; font-family: 'Arial',sans-serif;">You shall include your valid physical postal address in all emails.</span></li>
    <li style="margin-left: .25in; text-indent: -.25in; tab-stops: .5in;"><span style="font-size: 13.5pt; font-family: 'Arial',sans-serif;">You shall include a conspicuous notice in all marketing emails that the message is an advertisement or solicitation and that the recipient can opt out of receiving more commercial emails from you.</span></li>
</ul>
<p><span style="font-size: 13.5pt; font-family: 'Arial',sans-serif;">&nbsp;</span></p>
<p style="margin-bottom: 15.0pt;"><span style="font-size: 13.5pt; font-family: 'Arial',sans-serif;">We may, at any time, require you to prove that you have express permission to send emails to email addresses you have emailed.</span></p>
<p style="margin-bottom: 15.0pt;"><span style="font-size: 13.5pt; font-family: 'Arial',sans-serif;">Your use of Covered Services signifies your unconditional acceptance of this Anti-Spam Policy.</span></p>
<p><span style="font-size: 13.5pt; font-family: 'Arial',sans-serif;">&nbsp;</span></p>
<p style="margin-bottom: 15.0pt;"><span style="font-size: 13.5pt; font-family: 'Arial',sans-serif;">February 13, 2019</span></p>