<p style="text-align: center;" align="center"><strong>ibüümerang Subscription Terms and Conditions</strong></p>
<p style="text-align: center;" align="center">&nbsp;</p>
<p><span style="font-size: 10.0pt;">1. By establishing a Subscription Profile, I authorize IBuumerang to e-ship the subscription package I have selected each month. IBuumerang is under no obligation to e-ship subscriptions if the authorized credit card(s) have been closed, are expired, or the monthly limit exceeded. This Agreement does not supersede or modify in any way the policies and procedures of my IBuumerang Distributor Agreement. IBuumerang reserves the right to modify or terminate the Subscription programs in its sole discretion. </span></p>
<br>
<p><span style="font-size: 10.0pt;">2. PAYMENT AUTHORIZATION: I authorize IBuumerang to withdraw payment for my Subscription order(s) from my credit card(s) or bank account identified within my Subscription Profile. If I have elected to participate in the electronic checking program, I hereby authorize IBuumerang to electronically withdraw payment from my checking account for orders I placed directly and for Subscription orders as authorized in this Agreement. IBuumerang is authorized to withdraw payment equal only to the amount of the products and/or services, applicable sales tax, and shipping and handling of products that I order, or the Subscription orders I have selected. I agree to pay a $25.00 service fee in the event a check or charge is returned for any reason. I have the right to have the amount of any erroneous withdrawal deposited into my account as soon as reasonably possible and upon proper notification to IBuumerang. I shall hold IBuumerang harmless for all special or consequential damages, whether direct or indirect, resulting from any wrongful debit to my account. </span></p>
<br>
<p><span style="font-size: 10.0pt;">3. CHANGES: Changes can be made online by editing your Subscription Profile. Changes must be submitted to the company at least ten business days prior to Monthly Anniversary Date of any Subscription order. If more than one Subscription Agreement has been submitted, the most recent Agreement will supersede all previous Agreements. IBuumerang reserves the right to change its prices associated with its products without notice. In the event that sales taxes and/or shipping and handling charges have been incorrectly calculated, IBuumerang will adjust them to the proper amounts. </span></p>
<br>
<p><span style="font-size: 10.0pt;">4. TERM: This Agreement will remain in effect until you: (1) elect to alter or change any aspect of this Agreement by submitting a new Subscription Agreement or by changing your Subscription Profile online; (2) stop payment of any withdrawals by IBuumerang by notifying your issuing bank at least three days prior to the scheduled charging of your account. Notice of cancellation must be received ten business days before your Monthly Anniversary Date in order to avoid charges for that month. If a cancellation notice is received after ten business days before your Monthly Anniversary Date, cancellation will become effective in the month following the month in which your notice of cancellation is received by IBuumerang. </span></p>
<br>
<p><span style="font-size: 10.0pt;">5. SUBSCRIPTION DATE: If your join date falls between the 26th and the 31st of the month, your Subscription date will automatically become the 25th of the month even though the system may show your Subscription date as the 26th, 27th, etc., it will actually run on the 25th. Example: You become a IBuumerang Distributor on October 30th (Join Date), your Subscription date in November and all future months will be on the 25</span><span style="font-size: 6.0pt;">th</span><span style="font-size: 10.0pt;">. </span></p>
